export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR';

export const POST_CONTACT_TO_FRB_REQUEST = 'POST_CONTACT_TO_FRB_REQUEST';
export const POST_CONTACT_TO_FRB_ERROR = 'POST_CONTACT_TO_FRB_ERROR';
export const POST_CONTACT_TO_FRB_SUCCESS = 'POST_CONTACT_TO_FRB_SUCCESS';

export const VALUE_CHANGE = 'VALUE_CHANGE';

export const ADD_CONTACT_TO_FRB = 'ADD_CONTACT_TO_FRB';

export const CHANGE_CONTACT_FROM_FRB = 'CHANGE_CONTACT_FROM_FRB';
export const CHANGE_CONTACT_FROM_FRB_REQUEST = 'CHANGE_CONTACT_FROM_FRB_REQUEST';
export const CHANGE_CONTACT_FROM_FRB_ERROR = 'CHANGE_CONTACT_FROM_FRB_ERROR';

export const PRE_VIEW_CONTACT_REQUEST = 'PRE_VIEW_CONTACT_REQUEST';
export const PRE_VIEW_CONTACT_SUCCESS = 'PRE_VIEW_CONTACT_SUCCESS';
export const PRE_VIEW_CONTACT_ERROR = 'PRE_VIEW_CONTACT_ERROR';

export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';

export const SAVE_ID = 'SAVE_ID';

export const LOAD_CONTACT_SUCCESS = 'LOAD_CONTACT_SUCCESS';
export const LOAD_CONTACT_REQUEST = 'LOAD_CONTACT_REQUEST';
export const LOAD_CONTACT_ERROR = 'LOAD_CONTACT_ERROR';

export const DELETE_CONTACT_FROM_FRB = 'DELETE_CONTACT_FROM_FRB';
export const DELETE_CONTACT_FROM_FRB_ERROR = 'DELETE_CONTACT_FROM_FRB_ERROR';
export const DELETE_CONTACT_FROM_FRB_REQUEST = 'DELETE_CONTACT_FROM_FRB_REQUEST';