export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR';

export const POST_CONTACT_TO_FRB_REQUEST = 'POST_CONTACT_TO_FRB_REQUEST';
export const POST_CONTACT_TO_FRB_ERROR = 'POST_CONTACT_TO_FRB_ERROR';

export const VALUE_CHANGE = 'VALUE_CHANGE';